### ISSUE TITLE
Version

### ISSUE THREAD

**Issue by ghost** [ConciseCSS/concise.css-gem#2]
Is it compatible with version 3.1?

**Comment by keenanpayne** [comment]
@rezajatnika Unfortunately not! We are currently working on upgrading the gem so that is compatible with version 3.1. We will keep you posted, it should be coming soon!

**Comment by ghost** [comment]
Thanks @keenanpayne .

**Comment by jrasanen** [comment]
any news on gem for 3.1?

**Comment by ghost** [comment]
Just to let you know and for other users as well, currently this project is not supported and I don't have any plans to support it in the future, however, anyone who would like to take the task is very welcome. For now, I'll be focusing in the framework and all the add-ons.
